### ISSUE TITLE
[ bug ] Touching fingerprint key cannot wake up the device

### ISSUE THREAD

**Issue by VergeDX** [GZR-Kernels/Optimus_Drunk_Phoenix#1]
When my device sleeps for a few minutes, touching the fingerprint key (no press) does not work.  
So I must press the fingerprint key to wake up the device every time, and unlock via fingerprint.

My device is Redmi K30, and ROM is crDroid 6.5.  
If any logcat needed, please let me know.

@GtrCraft

**Comment by GtrCraft** [comment]
I have no such issue, can you give me logcat and fingerprint manufacture?

**Comment by VergeDX** [comment]
AIDA64 said that my fingerprint manufacture is "FPC" and the model is "FP"......  
Now I'm taking a logcat, but I did not find any suspicious errors......  
also, crDroid's fingerprint key behavior is abnormal...I cannot distinguish the valuable log...
https://github.com/crdroidandroid/android_device_xiaomi_phoenix/issues/2

@GtrCraft

**Comment by VergeDX** [comment]
I take a logcat via USB cable, and I found that when charging to phone, the problem will not appear...

**Comment by VergeDX** [comment]
Well, this issue still appears on my EU MIUI 11.0.15, when the screen turns black, and after a few minutes, the fingerprint sensor will be unavailable...  
If you need the log to debug, please let me know.  

@GtrCraft

**Comment by VergeDX** [comment]
And I also said that, If I plug it in the computer, this issue seems will not happen...
